package main.java.org.example;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this
 * license Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class GUIExpenseTracker extends javax.swing.JFrame {

    /**
     * Creates new form GUIExpenseTracker
     */

    String[] incomeCategories = new String[] {};
    String[] expenseCategories = new String[] {};
    String typeTrx = "Income";

    public GUIExpenseTracker() {
        incomeCategories = new String[] { "Gaji", "Pinjaman", "Lain-lain" };
        expenseCategories = new String[] { "Konsumsi", "Transport", "Kegiatan", "Hiburan", "Kesehatan",
                "Kebutuhan", "Darurat" };
        initComponents();
        populateReportTable(null, null, null);
        updateCategoryModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSpinner2 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        dateChooserPanel1 = new com.toedter.calendar.demo.DateChooserPanel();
        dateChooserPanelBeanInfo1 = new com.toedter.calendar.demo.DateChooserPanelBeanInfo();
        dateUtil1 = new com.toedter.calendar.DateUtil();
        demoTable1 = new com.toedter.calendar.demo.DemoTable();
        jCalendarBeanInfo1 = new com.toedter.calendar.JCalendarBeanInfo();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooserBeanInfo1 = new com.toedter.calendar.JDateChooserBeanInfo();
        jDateChooserCellEditor1 = new com.toedter.calendar.JDateChooserCellEditor();
        tabbepPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNominalTrx = new javax.swing.JTextField();
        txtKetTrx = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboCat = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSaveTrx = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtUserTrx = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        comTypeTrx = new javax.swing.JComboBox<>();
        dateTrx = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReport = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        dateChFrom = new com.toedter.calendar.JDateChooser();
        dateChUntil = new com.toedter.calendar.JDateChooser();
        buttonOkReport = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        buttonDeleteTx = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jDesktopPane1Layout.setVerticalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        jComboBox1.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
                jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jDesktopPane2Layout.setVerticalGroup(
                jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Rp");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtNominalTrx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNominalTrxActionPerformed(evt);
            }
        });

        txtKetTrx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKetTrxActionPerformed(evt);
            }
        });

        jLabel2.setText("Keterangan");

        jLabel3.setText("Kategori");

        jLabel4.setText("Tanggal");

        btnSaveTrx.setText("Save");
        btnSaveTrx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveTrxActionPerformed(evt);
            }
        });

        jLabel17.setText("User");

        txtUserTrx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserTrxActionPerformed(evt);
            }
        });

        jLabel18.setText("Tipe");

        comTypeTrx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Income", "Expense" }));
        comTypeTrx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comTypeTrxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(172, 172, 172)
                                                .addComponent(btnSaveTrx, javax.swing.GroupLayout.PREFERRED_SIZE, 72,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel2)
                                                                .addComponent(jLabel1,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jLabel17,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING))
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(txtNominalTrx)
                                                        .addComponent(txtKetTrx, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                110, Short.MAX_VALUE)
                                                        .addComponent(comTypeTrx,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(comboCat, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(dateTrx, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtUserTrx))))
                                .addContainerGap(197, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(txtUserTrx, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtNominalTrx, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtKetTrx, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(comTypeTrx, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(comboCat, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(dateTrx, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244,
                                        Short.MAX_VALUE)
                                .addComponent(btnSaveTrx)
                                .addGap(31, 31, 31)));

        tabbepPane3.addTab("Transaksi", jPanel2);

        tableReport.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null }
                },
                new String[] {
                        "ID", "Tanggal", "Keterangan", "Kategori", "Jenis", "Nominal", "User"
                }));
        jScrollPane1.setViewportView(tableReport);

        jLabel15.setText("Dari");

        jLabel16.setText("Sampai");

        buttonOkReport.setText("OK");
        buttonOkReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkReportActionPerformed(evt);
            }
        });

        jLabel6.setText("Cari");

        buttonDeleteTx.setText("Delete");
        buttonDeleteTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteTxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout
                                                .createSequentialGroup()
                                                .addGap(0, 4, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(jLabel6,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel15,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel4Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(dateChFrom, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                130, Short.MAX_VALUE)
                                                        .addComponent(txtSearch))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dateChUntil, javax.swing.GroupLayout.PREFERRED_SIZE, 130,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonDeleteTx)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonOkReport)
                                .addContainerGap()));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel16))
                                        .addComponent(dateChFrom, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dateChUntil, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonOkReport)
                                        .addComponent(buttonDeleteTx))
                                .addContainerGap(84, Short.MAX_VALUE)));

        tabbepPane3.addTab("Report", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tabbepPane3)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tabbepPane3)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkReportActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonOkReportActionPerformed
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableReport.getModel();
        model.setRowCount(0);
        Date from = dateChFrom.getDate();
        Date to = dateChUntil.getDate();
        String userName = txtSearch.getText().trim();

        if (from != null && to != null && to.before(from)) {
            showErrorMessageDialog("Masukan rentang tanggal yang valid!");
            return;
        }

        populateReportTable(from, to, userName);
    }// GEN-LAST:event_buttonOkReportActionPerformed

    private void txtUserTrxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtUserTrxActionPerformed

    }// GEN-LAST:event_txtUserTrxActionPerformed

    private void btnSaveTrxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveTrxActionPerformed
        try {
            String chosenType = comTypeTrx.getSelectedItem().toString();
            String txUserName = txtUserTrx.getText().trim();
            String txTitle = txtKetTrx.getText();
            String txCategory = comboCat.getSelectedItem().toString();
            Double txNominal = Double.parseDouble(txtNominalTrx.getText());
            saveTrx(chosenType, txUserName, txTitle, txCategory, txNominal);
            populateReportTable(null, null, null);
        } catch (NumberFormatException e) {
            showErrorMessageDialog("Masukkan nominal yang sesuai!");
        }
    }// GEN-LAST:event_btnSaveTrxActionPerformed

    private void txtKetTrxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtKetTrxActionPerformed

    }// GEN-LAST:event_txtKetTrxActionPerformed

    private void txtNominalTrxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNominalTrxActionPerformed

    }// GEN-LAST:event_txtNominalTrxActionPerformed

    private void buttonDeleteTxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonDeleteTxActionPerformed

    }// GEN-LAST:event_buttonDeleteTxActionPerformed

    private void comTypeTrxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comTypeTrxActionPerformed
        String chosen = comTypeTrx.getSelectedItem().toString();
        if (chosen.equals("Income")) {
            this.typeTrx = "Income";
            updateCategoryModel();
        } else {
            this.typeTrx = "Expense";
            updateCategoryModel();
        }
    }// GEN-LAST:event_comTypeTrxActionPerformed

    private void updateCategoryModel() {
        if (this.typeTrx.equalsIgnoreCase("Income")) {
            comboCat.setModel(new javax.swing.DefaultComboBoxModel<>(this.incomeCategories));
        } else {
            comboCat.setModel(new javax.swing.DefaultComboBoxModel<>(this.expenseCategories));
        }
    }

    private void saveTrx(String trxType, String username, String title, String category,
            double nominal) {
        try {
            if (nominal < 0) {
                throw new NumberFormatException();
            }

            LocalDate now = LocalDate.now();

            User user = new User(username);
            Transaction txIncome;
            if (trxType.equals("Income")) {
                txIncome = new Income(title, category, nominal, now, user);
            } else {
                txIncome = new Expense(title, category, nominal, now, user);
            }
            TransactionHandler.saveTransaction(txIncome);
            showInformationMessageDialog("Transaksi berhasil disimpan!");
            txtNominalTrx.setText("");
        } catch (NumberFormatException e) {
            showErrorMessageDialog("Masukkan nominal yang sesuai!");
        }
    }

    private void populateReportTable(Date from, Date until, String userName) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableReport.getModel();
        model.setRowCount(0);
        ArrayList<String> txs;

        if (from == null || until == null) {
            System.out.println("masuk null");
            txs = TransactionHandler.getTransactions(null, null, userName);
        } else {
            System.out.println("masuk sini");
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

            Date dateFrom = from;
            String _from = dateFormat.format(dateFrom);

            Date dateTo = until;
            String _until = dateFormat.format(dateTo);

            txs = TransactionHandler.getTransactions(_from, _until);
        }

        for (String tx : txs) {
            String[] txDetails = tx.split(", ");
            Object[] newRow = { txDetails[0], txDetails[1], txDetails[2], txDetails[3], txDetails[4], txDetails[5], txDetails[6] };
            model.addRow(newRow);
        }
    }

    protected static void showErrorMessageDialog(String message) {
        JOptionPane.showMessageDialog(null, message, "Information", JOptionPane.ERROR_MESSAGE);
    }

    protected static void showInformationMessageDialog(String message) {
        JOptionPane.showMessageDialog(null, message, "Information", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIExpenseTracker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveTrx;
    private javax.swing.JButton buttonDeleteTx;
    private javax.swing.JButton buttonOkReport;
    private javax.swing.JComboBox<String> comTypeTrx;
    private javax.swing.JComboBox<String> comboCat;
    private com.toedter.calendar.JDateChooser dateChFrom;
    private com.toedter.calendar.JDateChooser dateChUntil;
    private com.toedter.calendar.demo.DateChooserPanel dateChooserPanel1;
    private com.toedter.calendar.demo.DateChooserPanelBeanInfo dateChooserPanelBeanInfo1;
    private com.toedter.calendar.JDateChooser dateTrx;
    private com.toedter.calendar.DateUtil dateUtil1;
    private com.toedter.calendar.demo.DemoTable demoTable1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendarBeanInfo jCalendarBeanInfo1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooserBeanInfo jDateChooserBeanInfo1;
    private com.toedter.calendar.JDateChooserCellEditor jDateChooserCellEditor1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane tabbepPane3;
    private javax.swing.JTable tableReport;
    private javax.swing.JTextField txtKetTrx;
    private javax.swing.JTextField txtNominalTrx;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUserTrx;
    // End of variables declaration//GEN-END:variables
}
